[versions]
datastore = "1.2.0"
compose = "1.10.1"
detekt = "1.23.8"
glance = "1.1.1"
koin = "4.1.1"
kotest = "6.1.2"
kotlin = "2.3.0"
licensee = "1.14.1"
vanpra-material-dialogs = "0.9.0"
sqldelight = "2.2.1"
mockk = "1.14.6"
review = "2.0.2"

[libraries]
android-desugar-jdk = "com.android.tools:desugar_jdk_libs:2.1.5"
apache-commons-lang = "org.apache.commons:commons-lang3:3.20.0"
apache-commons-math = "org.apache.commons:commons-math3:3.6.1"
compose-activity = "androidx.activity:activity-compose:1.10.1"
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-dialogs-core = { module = "io.github.vanpra.compose-material-dialogs:core", version.ref = "vanpra-material-dialogs" }
compose-material-dialogs-date-time = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "vanpra-material-dialogs" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
compose-material-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-navigation = "androidx.navigation:navigation-compose:2.9.6"
compose-tabler-icons = "br.com.devsrsouza.compose.icons:tabler-icons:1.1.1"
compose-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
datastore-android = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
graph-view = "com.jjoe64:graphview:4.2.2"
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner-android = { module = "br.com.colman:kotest-runner-android", version = "1.2.2" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotlin-csv = "com.jsoizo:kotlin-csv:1.10.0"
kotlin-date-range = "me.moallemi.tools:kotlin-date-range:1.0.0"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mp-android-chart = "com.github.AppDevNext:AndroidChart:3.1.0.31"
snodge = "com.natpryce:snodge:3.7.0.0"
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
timber = "com.jakewharton.timber:timber:5.0.1"
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-sqlite-dialect = { module = "app.cash.sqldelight:sqlite-3-25-dialect", version.ref = "sqldelight" }
requery-sqlite = "com.github.requery:sqlite-android:3.49.0"
glance = { module = "androidx.glance:glance", version.ref = "glance" }
glance-widgets = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-widget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }
glance-material = { group = "androidx.glance", name = "glance-material", version.ref = "glance" }
play-services-ads = "com.google.android.gms:play-services-ads:24.9.0"
play-services-billing = "com.android.billingclient:billing:8.3.0"
fuel = "com.github.kittinunf.fuel:fuel:2.3.1"
androidx-test-core = "androidx.test:core:1.7.0"
review = { module = "com.google.android.play:review", version.ref = "review" }


[bundles]
review = ["review"]
androidx-test = [
    "androidx-test-core",
]
apache-commons = [
    "apache-commons-lang",
    "apache-commons-math",
]
compose = [
    "compose-activity",
    "compose-material",
    "compose-material-dialogs-core",
    "compose-material-dialogs-date-time",
    "compose-material-icons",
    "compose-navigation",
    "compose-tabler-icons",
]
compose-test = [
    "compose-ui-test",
]
datastore = [
    "datastore-android",
    "datastore-core",
]
date-time = [
    "kotlin-date-range",
]
glance = ["glance", "glance-widgets", "glance-widget-preview", "glance-preview","glance-material"]
graph-view = [
    "graph-view",
    "mp-android-chart",
]
koin = [
    "koin-android",
    "koin-compose",
]
kotest-jvm = ["kotest-runner-junit5"]
kotest-android = ["kotest-runner-android"]
kotest-common = ["kotest-assertions", "kotest-property"]
mockk-android = ["mockk-android", "mockk-agent"]


[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.4" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }