naming:
  FunctionNaming:
    ignoreAnnotated: [Composable]
formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
  NoWildcardImports:
    active: false